#!/bin/bash
#
#BSUB -W 24:00                          # 24 hours of walltime requested
#BSUB -n 1                            # number of tasks in job; we get (4 nodes x 40 CPU slots), one gpu node has 40 cpu slots
#BSUB -R "span[ptile=1]"
#BSUB -q gpu_p100                       # choose the queue to use: normal or large_memory
#BSUB -u fanlai@umich.edu                 # email address to send notifications

source /gpfs/gpfs0/groups/chowdhury/fanlai/pytorch_install.sh
source activate mytorch

