#!/bin/bash
#
#BSUB -W 2:00                          # 6 hours of walltime requested
#BSUB -n 25                            # number of tasks in job; we get (4 nodes x 40 CPU slots), one gpu node has 40 cpu slots
#BSUB -R "span[ptile=25]"               # limit 40 processes per node. See note above about HT
#BSUB -q gpu_p100                       # choose the queue to use: normal or large_memory
#BSUB -u fanlai@umich.edu                 # email address to send notifications
#rm /tmp/torch/*
#BSUB -m "gpu-cn001"
#BSUB -J test
#BSUB -e test.e
#BSUB -o test.o

source /gpfs/gpfs0/groups/chowdhury/fanlai/pytorch_install.sh
source activate mypytorch
python ~/DMFL/tests/testtorch.py
